// Generate the endpoint reference pages from public/openapi.json.
// Output is committed; re-run after `npm run fetch:openapi`.
import { readFile, rm, writeFile } from 'node:fs/promises';
import { generateFiles } from 'fumadocs-openapi';
import { createOpenAPI } from 'fumadocs-openapi/server';

const OUT = './content/docs/developers/reference';
const ORDER = ['markets', 'oracle', 'trading', 'positions', 'account', 'vaults', 'referral', 'leaderboard', 'keys', 'system'];
const openapi = createOpenAPI({ input: ['./public/openapi.json'] });

await rm(OUT, { recursive: true, force: true });
await generateFiles({
  input: openapi,
  output: OUT,
  per: 'operation',
  groupBy: 'tag',
  includeDescription: true,
  addGeneratedComment: true,
  meta: true,
});

// Post-process: ordered folder meta and a hand-rolled index listing every route.
const spec = JSON.parse(await readFile('./public/openapi.json', 'utf8'));
const display = Object.fromEntries((spec.tags ?? []).map((t) => [t.name, t['x-displayName'] ?? t.name]));
const groups = new Map();
for (const [path, item] of Object.entries(spec.paths)) {
  for (const method of ['get', 'post', 'put', 'patch', 'delete']) {
    const op = item[method];
    if (!op) continue;
    const tag = op.tags?.[0] ?? 'system';
    if (!groups.has(tag)) groups.set(tag, []);
    const firstSentence = (op.description ?? '').split(/(?<=\.)\s/)[0].replace(/\s+/g, ' ').trim();
    groups.get(tag).push({ method: method.toUpperCase(), path, slug: `${tag}/${op.operationId}`, blurb: firstSentence });
  }
}
const tagsInOrder = [...ORDER.filter((t) => groups.has(t)), ...[...groups.keys()].filter((t) => !ORDER.includes(t))];
await writeFile(`${OUT}/meta.json`, JSON.stringify({ title: 'Endpoint reference', pages: [...tagsInOrder] }, null, 2) + '\n');

const authNote = 'A bearer API key is required for `/v1/account/*`, `/v1/referral/me*`, `POST /v1/orders/prepare`, `POST /v1/tx/submit`, and for listing or deleting keys; everything else is public. The playground sends requests through the docs server, so a key you paste there passes through it.';
let index = `---\ntitle: Endpoint reference\ndescription: Every gateway route, generated from the live OpenAPI spec, with request samples in curl, JavaScript and Python and a playground you can run against testnet.\n---\n\n{/* Generated by scripts/generate-api.mjs. Do not edit by hand. */}\n\nBase URL: \`${spec.servers?.[0]?.url ?? ''}\`. ${authNote} Amounts and prices are strings of 7-decimal fixed-point integers.\n\n`;
for (const tag of tagsInOrder) {
  index += `## ${display[tag] ?? tag}\n\n`;
  for (const op of groups.get(tag)) {
    index += `- [\`${op.method} ${op.path}\`](/developers/reference/${op.slug})${op.blurb ? ` — ${op.blurb}` : ''}\n`;
  }
  index += '\n';
}
await writeFile(`${OUT}/index.mdx`, index);
console.log(`generated ${[...groups.values()].flat().length} endpoint pages in ${tagsInOrder.length} groups -> ${OUT}`);
